import type { Metadata } from "next";
import localFont from "next/font/local";
import {
  ClerkProvider,
} from '@clerk/nextjs'

import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { QueryProviders } from '@/providers/query-provider'; // Adjust the path as necessary
import { SheetProvider } from "@/providers/sheet-provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Budget Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <QueryProviders>
            <SheetProvider/>
            <Toaster />
                 {children}   
          </QueryProviders>
        </body>
      </html>
    </ClerkProvider>
  );
};
